TARGET		= tricked_out.elf

SRCS		= vu1_renderers.vsm

INCDIRS		= $(PS2GL)/vu1
ASMINCDIRS	= $(PS2GL)/vu1

LIBS		= ps2gl_sample

# all the examples share the same makefile, just with a different
# executable name..
include ../shared_code/Makefile.examples